# Generated by Django 4.1.3 on 2023-01-30 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0002_author_book_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="author",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.DeleteModel(name="Author",),
    ]
